export const mockData = [   // https://github.com/Marlon-Paulo-da-Silva/TikTok-Clone-ReactNative/blob/master/server.json
      {
        "id": 1,
        "video_url": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
        "aspectRatio": 0.834,
        "description": "Trabalhando Muito!!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 2,
        "video_url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
        "aspectRatio": 0.834,
        "description": "Sleep, eat, code, repeat!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",      },
      {
        "id": 3,
        "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "aspectRatio": 0.834,
        "description": "Rocketships fly away!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 4,
        "video_url": "http://techslides.com/demos/sample-videos/small.mp4",
        "aspectRatio": 0.834,
        "description": "3, 2, 1, ready to launch!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 5,
        "video_url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
        "aspectRatio": 0.834,
        "description": "Code, code and more code!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 6,
        "video_url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
        "aspectRatio": 0.834,
        "description": "Node.js + ReactJS + React Native = <3",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 7,
        "video_url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
        "aspectRatio": 0.834,
        "description": "OmniStack to the rescue!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 8,
        "video_url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "aspectRatio": 0.834,
        "description": "Rocketseat is cool!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 9,

        "video_url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
        "aspectRatio": 0.834,
        "description": "Have you watched our videos at YouTube?",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 10,
        "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        "aspectRatio": 0.834,
        "description": "Code, code and more code!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 11,
        "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "aspectRatio": 0.834,
        "description": "Developing new great app!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 12,
        "video_url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        "aspectRatio": 0.834,
        "description": "Let's code everyday!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 13,
        "video_url": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
        "aspectRatio": 0.834,
        "description": "Sleep, eat, code, repeat!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      {
        "id": 14,
        "video_url": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
        "aspectRatio": 0.834,
        "description": "Working hard at Rocketseat!",
        "likes": 1002,
        "hashtags": "#Work #Dev",
        "place": "Cinema do PrudenShopping",
      },
      // {
      //   "id": 15,
      //   "video_url": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
      //   "aspectRatio": 0.834,
      //   "description": "Code, code and more code!",
      //   "likes": 1002,
      //   "hashtags": "#Work #Dev",
      //   "place": "Cinema do PrudenShopping",
      // },
      // {
      //   "id": 16,
      //   "video_url": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
      //   "aspectRatio": 0.834,
      //   "description": "Just studying some React Native stuff!",
      //   "likes": 1002,
      //   "hashtags": "#Work #Dev",
      //   "place": "Cinema do PrudenShopping",
      // },
      // {
      //   "id": 17,
      //   "video_url": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
      //   "aspectRatio": 0.834,
      //   "description": "React Native is such a great tool by Facebook!",
      //   "likes": 1002,
      //   "hashtags": "#Work #Dev",
      //   "place": "Cinema do PrudenShopping",
      // },
      // {
      //   "id": 18,
      //   "video_url": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
      //   "aspectRatio": 0.834,
      //   "description": "Love what you do, do what you love!",
      //   "likes": 1002,
      //   "hashtags": "#Work #Dev",
      //   "place": "Cinema do PrudenShopping",
      // },
      // {
      //   "id": 19,
      //   "video_url": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
      //   "aspectRatio": 0.834,
      //   "description": "Code, code and more code!",
      //   "likes": 1002,
      //   "hashtags": "#Work #Dev",
      //   "place": "Cinema do PrudenShopping",
      // },
      // {
      //   "id": 20,
      //   "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      //   "aspectRatio": 0.834,
      //   "description": "Code, code and more code!",
      //   "likes": 1002,
      //   "hashtags": "#Work #Dev",
      //   "place": "Cinema do PrudenShopping",

      // }
    ]